name: Deploy Angular App to Azure Storage

on:
  push:
    branches: [ "main" ] 

env:
  AZURE_STORAGE_ACCOUNT: 'el7erafewebdashboard'
  AZURE_STORAGE_CONTAINER: '$web'
  NODE_VERSION: '18.x'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check if the package-lock.json exists
      run: |
        ls -la
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found!"
          exit 1
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci  #Only downloads changed packages

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Build application
      run: npm run build -- --configuration production
      env:
        NODE_ENV: production

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 1

  deploy-to-staging:
    if: github.ref == 'refs/heads/main'
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files

    - name: Deploy to Azure Storage
      env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      uses: azure/CLI@v1
      with:
        azcliversion: 2.40.0
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }}-production \
            --source ./dist/your-app-name \
            --destination '$web' \
            --overwrite
        
